package com.activity.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.activity.greendao.SuiDao;

import com.activity.greendao.SuiDaoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig suiDaoDaoConfig;

    private final SuiDaoDao suiDaoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        suiDaoDaoConfig = daoConfigMap.get(SuiDaoDao.class).clone();
        suiDaoDaoConfig.initIdentityScope(type);

        suiDaoDao = new SuiDaoDao(suiDaoDaoConfig, this);

        registerDao(SuiDao.class, suiDaoDao);
    }
    
    public void clear() {
        suiDaoDaoConfig.clearIdentityScope();
    }

    public SuiDaoDao getSuiDaoDao() {
        return suiDaoDao;
    }

}
